name: flutter_native_colorpicker
description: Use native color pickers shipped with the OS.
version: 2.0.1
homepage: https://github.com/cloudacy/flutter_native_colorpicker

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.cloudacy.flutter_native_colorpicker
        pluginClass: FlutterNativeColorpickerPlugin
      ios:
        pluginClass: FlutterNativeColorpickerPlugin
